### ISSUE TITLE
Other projects with the same idea

### ISSUE THREAD

**Issue by rugk** [dbrgn/xkcdpass-rs#4]
https://github.com/beala/xkcd-password
https://github.com/redacted/XKCD-password-generator
https://github.com/fardog/node-xkcd-password

You might get some ideas from there. Also you should clarify (in the Readme) why one should use your project instead of all the other password generators, which already exist.

**Comment by dbrgn** [comment]
> Also you should clarify (in the Readme) why one should use your project instead of all the other password generators, which already exist.

I don't know if people should. I simply scratched my own itch. The project will probably never be as complex as some of the links you posted.

**Comment by rugk** [comment]
Okay, good to know anyway. Rust rocks! 😃
