### ISSUE TITLE
Strange words in wordlist.

### ISSUE THREAD

**Issue by user6553591** [dbrgn/xkcdpass-rs#7]
Like this: https://github.com/dbrgn/xkcdpass-rs/blob/master/src/wordlist.txt#L90
And this: https://github.com/dbrgn/xkcdpass-rs/blob/master/src/wordlist.txt#L205

**Comment by dbrgn** [comment]
You're right. I should probably switch to the [EFF long list](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases) by default.
